/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    programs: Program;
    resources: Resource;
    testimonials: Testimonial;
    quotes: Quote;
    events: Event;
    gallery: Gallery;
    challenges: Challenge;
    members: Member;
    'check-ins': CheckIn;
    badges: Badge;
    'member-badges': MemberBadge;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    challenges: ChallengesSelect<false> | ChallengesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'check-ins': CheckInsSelect<false> | CheckInsSelect<true>;
    badges: BadgesSelect<false> | BadgesSelect<true>;
    'member-badges': MemberBadgesSelect<false> | MemberBadgesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-walt': AboutWalt;
    'contact-page': ContactPage;
    'community-stats': CommunityStat;
    'quote-settings': QuoteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-walt': AboutWaltSelect<false> | AboutWaltSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'community-stats': CommunityStatsSelect<false> | CommunityStatsSelect<true>;
    'quote-settings': QuoteSettingsSelect<false> | QuoteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * People who can sign in to the admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name shown in the admin panel.
   */
  name: string;
  /**
   * Administrators manage users and system settings. Editors update website content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images used across the website. Prefer JPEG, PNG, or WebP under 5MB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description of the image for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Programs and services for nutrition, fitness, mindset, and healthy lifestyle habits.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  name: string;
  /**
   * URL-friendly name (e.g. nutrition-coaching). Used in /programs/nutrition-coaching
   */
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short blurb shown on cards and the home page.
   */
  summary?: string | null;
  image?: (number | null) | Media;
  category?: ('nutrition' | 'fitness' | 'mindset' | 'lifestyle' | 'community' | 'other') | null;
  /**
   * Optional. Leave blank if members should inquire for details.
   */
  pricing?: {
    showPrice?: boolean | null;
    /**
     * e.g. Free for members, From $49, Included
     */
    priceLabel?: string | null;
    /**
     * Optional note under the price.
     */
    priceNote?: string | null;
  };
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Uncheck to hide this program from the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles, tips, and resources on nutrition, fitness, mindset, and healthy habits.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * URL-friendly name (e.g. feeling-good-habits).
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short teaser for listing cards.
   */
  summary?: string | null;
  featuredImage?: (number | null) | Media;
  category?: ('nutrition' | 'fitness' | 'mindset' | 'lifestyle' | 'community' | 'general') | null;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Member stories and quotes that inspire lasting positive change.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  memberName: string;
  quote: string;
  /**
   * Optional role or context (e.g. Community member, Challenge graduate).
   */
  role?: string | null;
  photo?: (number | null) | Media;
  /**
   * Featured testimonials may appear on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quotes shown on the front page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  quote: string;
  /**
   * Who said the quote (e.g. Marcus Aurelius).
   */
  attribution?: string | null;
  /**
   * Include this quote in the front-page rotation.
   */
  active?: boolean | null;
  /**
   * Lower numbers appear first (used for deterministic day/week rotation).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community gatherings, workshops, challenges kickoffs, and wellness events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL-friendly name (e.g. spring-wellness-meetup).
   */
  slug: string;
  /**
   * Short blurb for event cards.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  startDate: string;
  endDate?: string | null;
  /**
   * Venue name, address, or “Online”.
   */
  location?: string | null;
  /**
   * Optional external signup link.
   */
  registrationUrl?: string | null;
  /**
   * Uncheck to hide this event from the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos from the community, events, challenges, and everyday wins.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image: number | Media;
  caption?: string | null;
  category?: ('general' | 'community' | 'events' | 'challenges' | 'nutrition' | 'fitness' | 'mindset') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wellness challenges that inspire lasting positive change in the community.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges".
 */
export interface Challenge {
  id: number;
  title: string;
  /**
   * URL-friendly name (e.g. 30-day-habit-reset).
   */
  slug: string;
  /**
   * Short blurb for challenge cards.
   */
  summary?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  startDate?: string | null;
  endDate?: string | null;
  status: 'draft' | 'upcoming' | 'active' | 'completed';
  /**
   * Optional link for members to join the challenge.
   */
  joinUrl?: string | null;
  /**
   * Featured challenges may appear on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community members who sign in on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  /**
   * Shown on the community feed, leaderboard, and badges.
   */
  displayName: string;
  avatar?: (number | null) | Media;
  bio?: string | null;
  /**
   * Staff-managed account status. Members cannot change this.
   */
  status: 'active' | 'pending' | 'suspended';
  totalCheckIns?: number | null;
  currentStreak?: number | null;
  longestStreak?: number | null;
  lastCheckInDate?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * Member check-ins. Creating one updates member stats and badge progress automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "check-ins".
 */
export interface CheckIn {
  id: number;
  /**
   * Defaults to the logged-in member; staff can log check-ins on behalf of a member.
   */
  member: number | Member;
  /**
   * Optional — link this check-in to a specific challenge.
   */
  challenge?: (number | null) | Challenge;
  note?: string | null;
  checkInDate: string;
  /**
   * UTC day of the check-in. Set automatically.
   */
  checkInDay?: string | null;
  /**
   * `{memberId}:{YYYY-MM-DD}` — enforces one check-in per member per day.
   */
  checkInKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Badge definitions. Adding a row here creates a new badge — no code change needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges".
 */
export interface Badge {
  id: number;
  name: string;
  description?: string | null;
  icon?: (number | null) | Media;
  /**
   * What member stat this badge is awarded for.
   */
  criteriaType: 'checkin_count' | 'streak_length';
  /**
   * Threshold the stat must reach, e.g. 7 for a 7-day streak.
   */
  criteriaValue: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Records of badges members have earned. Created automatically by the check-in hook.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-badges".
 */
export interface MemberBadge {
  id: number;
  member: number | Member;
  badge: number | Badge;
  awardedAt: string;
  /**
   * `{memberId}:{badgeId}` — prevents duplicate badge awards.
   */
  awardKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'challenges';
        value: number | Challenge;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'check-ins';
        value: number | CheckIn;
      } | null)
    | ({
        relationTo: 'badges';
        value: number | Badge;
      } | null)
    | ({
        relationTo: 'member-badges';
        value: number | MemberBadge;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  summary?: T;
  image?: T;
  category?: T;
  pricing?:
    | T
    | {
        showPrice?: T;
        priceLabel?: T;
        priceNote?: T;
      };
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  summary?: T;
  featuredImage?: T;
  category?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  memberName?: T;
  quote?: T;
  role?: T;
  photo?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  image?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  registrationUrl?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges_select".
 */
export interface ChallengesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  image?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  joinUrl?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  displayName?: T;
  avatar?: T;
  bio?: T;
  status?: T;
  totalCheckIns?: T;
  currentStreak?: T;
  longestStreak?: T;
  lastCheckInDate?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "check-ins_select".
 */
export interface CheckInsSelect<T extends boolean = true> {
  member?: T;
  challenge?: T;
  note?: T;
  checkInDate?: T;
  checkInDay?: T;
  checkInKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges_select".
 */
export interface BadgesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  criteriaType?: T;
  criteriaValue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-badges_select".
 */
export interface MemberBadgesSelect<T extends boolean = true> {
  member?: T;
  badge?: T;
  awardedAt?: T;
  awardKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Community identity, contact details, and social links used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  businessName: string;
  /**
   * Short line under the community name (optional).
   */
  tagline?: string | null;
  logo?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  /**
   * Links shown in the header/footer.
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok' | 'other';
        url: string;
        /**
         * Optional custom label (mainly for “Other”).
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  hours?:
    | {
        /**
         * e.g. Monday–Friday, Saturday
         */
        day: string;
        /**
         * e.g. 9:00 AM – 5:00 PM or Closed
         */
        hours: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the public homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Large image at the top of the homepage.
   */
  heroImage?: (number | null) | Media;
  /**
   * Background image that starts immediately below the hero image (top of this image aligns to bottom of hero).
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Opacity of the background image (0 = transparent, 100 = fully opaque).
   */
  backgroundOpacity?: number | null;
  headline: string;
  subheadline?: string | null;
  /**
   * Main introduction paragraph(s) under the hero.
   */
  introduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Pick programs to highlight on the homepage. Leave empty to show the first few published programs.
   */
  featuredPrograms?: (number | Program)[] | null;
  cta?: {
    heading?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    /**
     * Internal path (e.g. /contact) or full URL.
     */
    buttonLink?: string | null;
    /**
     * Secondary text displayed next to the CTA button.
     */
    secondaryText?: string | null;
  };
  /**
   * Add, reorder, and configure text blocks on a 12-column grid. Each block can be positioned independently and styled with font size and color.
   */
  contentBlocks?:
    | (
        | {
            /**
             * The text content to display.
             */
            text: string;
            /**
             * Starting column (1–12) on the 12-column grid.
             */
            columnStart?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            /**
             * How many columns this block spans (1–12).
             */
            columnSpan?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            /**
             * Starting row (1–10, or Auto for default flow).
             */
            rowStart?: ('auto' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
            /**
             * How many rows this block spans (1–6, or Auto).
             */
            rowSpan?: ('auto' | '1' | '2' | '3' | '4' | '5' | '6') | null;
            /**
             * Font family from the imported fonts.
             */
            fontFamily?:
              | (
                  | 'manrope'
                  | 'manrope-semibold'
                  | 'manrope-bold'
                  | 'manrope-extrabold'
                  | 'archivo-black'
                  | 'montserrat-bold'
                  | 'montserrat-extrabold'
                  | 'eb-garamond-italic'
                  | 'eb-garamond-medium-italic'
                  | 'eb-garamond-semibold-italic'
                )
              | null;
            /**
             * Font size in points (8–128).
             */
            fontSize?: string | null;
            /**
             * Font color from the brand palette.
             */
            fontColor?:
              | (
                  | 'stone-900'
                  | 'stone-800'
                  | 'stone-700'
                  | 'stone-600'
                  | 'brand-900'
                  | 'brand-800'
                  | 'brand-700'
                  | 'brand-600'
                  | 'white'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            /**
             * The quote text.
             */
            quote: string;
            /**
             * Who said the quote (e.g. name, title).
             */
            attribution?: string | null;
            /**
             * Starting column (1–12) on the 12-column grid.
             */
            columnStart?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            /**
             * How many columns this block spans (1–12).
             */
            columnSpan?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            /**
             * Starting row (1–10, or Auto for default flow).
             */
            rowStart?: ('auto' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
            /**
             * How many rows this block spans (1–6, or Auto).
             */
            rowSpan?: ('auto' | '1' | '2' | '3' | '4' | '5' | '6') | null;
            /**
             * Font family for the quote text.
             */
            quoteFontFamily?:
              | (
                  | 'manrope'
                  | 'manrope-semibold'
                  | 'manrope-bold'
                  | 'manrope-extrabold'
                  | 'archivo-black'
                  | 'montserrat-bold'
                  | 'montserrat-extrabold'
                  | 'eb-garamond-italic'
                  | 'eb-garamond-medium-italic'
                  | 'eb-garamond-semibold-italic'
                )
              | null;
            /**
             * Font size in points (8–128).
             */
            quoteFontSize?: string | null;
            /**
             * Font color for the quote text.
             */
            quoteFontColor?:
              | (
                  | 'stone-900'
                  | 'stone-800'
                  | 'stone-700'
                  | 'stone-600'
                  | 'brand-900'
                  | 'brand-800'
                  | 'brand-700'
                  | 'brand-600'
                  | 'white'
                )
              | null;
            /**
             * Font family for the attribution text.
             */
            attributionFontFamily?:
              | (
                  | 'manrope'
                  | 'manrope-semibold'
                  | 'manrope-bold'
                  | 'manrope-extrabold'
                  | 'archivo-black'
                  | 'montserrat-bold'
                  | 'montserrat-extrabold'
                  | 'eb-garamond-italic'
                  | 'eb-garamond-medium-italic'
                  | 'eb-garamond-semibold-italic'
                )
              | null;
            /**
             * Font size in points (8–128).
             */
            attributionFontSize?: string | null;
            /**
             * Font color for the attribution text.
             */
            attributionFontColor?:
              | (
                  | 'stone-900'
                  | 'stone-800'
                  | 'stone-700'
                  | 'stone-600'
                  | 'brand-900'
                  | 'brand-800'
                  | 'brand-700'
                  | 'brand-600'
                  | 'white'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            /**
             * Starting column (1–12) on the 12-column grid.
             */
            columnStart?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            /**
             * How many columns this block spans (1–12).
             */
            columnSpan?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            /**
             * Starting row (1–10, or Auto for default flow).
             */
            rowStart?: ('auto' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
            /**
             * How many rows this block spans (1–6, or Auto).
             */
            rowSpan?: ('auto' | '1' | '2' | '3' | '4' | '5' | '6') | null;
            /**
             * Font family for the quote text.
             */
            quoteFontFamily?:
              | (
                  | 'manrope'
                  | 'manrope-semibold'
                  | 'manrope-bold'
                  | 'manrope-extrabold'
                  | 'archivo-black'
                  | 'montserrat-bold'
                  | 'montserrat-extrabold'
                  | 'eb-garamond-italic'
                  | 'eb-garamond-medium-italic'
                  | 'eb-garamond-semibold-italic'
                )
              | null;
            /**
             * Font size in points (8–128).
             */
            quoteFontSize?: string | null;
            /**
             * Font color for the quote text.
             */
            quoteFontColor?:
              | (
                  | 'stone-900'
                  | 'stone-800'
                  | 'stone-700'
                  | 'stone-600'
                  | 'brand-900'
                  | 'brand-800'
                  | 'brand-700'
                  | 'brand-600'
                  | 'white'
                )
              | null;
            /**
             * Font family for the attribution text.
             */
            attributionFontFamily?:
              | (
                  | 'manrope'
                  | 'manrope-semibold'
                  | 'manrope-bold'
                  | 'manrope-extrabold'
                  | 'archivo-black'
                  | 'montserrat-bold'
                  | 'montserrat-extrabold'
                  | 'eb-garamond-italic'
                  | 'eb-garamond-medium-italic'
                  | 'eb-garamond-semibold-italic'
                )
              | null;
            /**
             * Font size in points (8–128).
             */
            attributionFontSize?: string | null;
            /**
             * Font color for the attribution text.
             */
            attributionFontColor?:
              | (
                  | 'stone-900'
                  | 'stone-800'
                  | 'stone-700'
                  | 'stone-600'
                  | 'brand-900'
                  | 'brand-800'
                  | 'brand-700'
                  | 'brand-600'
                  | 'white'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamicQuote';
          }
        | {
            /**
             * The image to display.
             */
            image: number | Media;
            /**
             * Starting column (1–12) on the 12-column grid.
             */
            columnStart?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            /**
             * How many columns this block spans (1–12).
             */
            columnSpan?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            /**
             * Starting row (1–10, or Auto for default flow).
             */
            rowStart?: ('auto' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
            /**
             * How many rows this block spans (1–6, or Auto).
             */
            rowSpan?: ('auto' | '1' | '2' | '3' | '4' | '5' | '6') | null;
            /**
             * How the image fills its container.
             */
            objectFit?: ('cover' | 'contain' | 'fill' | 'none' | 'scale-down') | null;
            /**
             * CSS object-position value (e.g. center, top, 50% 20%). Use % values to keep the soldier's head/torso visible.
             */
            objectPosition?: string | null;
            /**
             * Override the media's alt text for accessibility. Leave empty to use the media default.
             */
            alt?: string | null;
            /**
             * Optional caption displayed below the image.
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Story, mission, and philosophy for the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-walt".
 */
export interface AboutWalt {
  id: number;
  headline: string;
  subheadline?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Main about story and mission.
   */
  introduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Core philosophy quote shown on the About page.
   */
  philosophy?: string | null;
  /**
   * Pillars such as nutrition, fitness, mindset, and lifestyle.
   */
  focusAreas?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional photo of Walt or the community.
   */
  portrait?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for the public contact page. Phone, email, and address live in Site Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  headline: string;
  intro?: string | null;
  /**
   * Optional note under contact details (e.g. response times).
   */
  formNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Community-wide totals shown on the home page. Kept in sync by the CheckIns hook — avoid hand-editing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-stats".
 */
export interface CommunityStat {
  id: number;
  totalMembers?: number | null;
  totalCheckIns?: number | null;
  totalBadgesAwarded?: number | null;
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls how the front-page quote is chosen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-settings".
 */
export interface QuoteSetting {
  id: number;
  /**
   * How often a new quote appears.
   */
  rotationMode?: ('page-load' | 'session' | 'day' | 'week') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  tagline?: T;
  logo?: T;
  phone?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  hours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroImage?: T;
  backgroundImage?: T;
  backgroundOpacity?: T;
  headline?: T;
  subheadline?: T;
  introduction?: T;
  featuredPrograms?: T;
  cta?:
    | T
    | {
        heading?: T;
        text?: T;
        buttonLabel?: T;
        buttonLink?: T;
        secondaryText?: T;
      };
  contentBlocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              text?: T;
              columnStart?: T;
              columnSpan?: T;
              rowStart?: T;
              rowSpan?: T;
              fontFamily?: T;
              fontSize?: T;
              fontColor?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              columnStart?: T;
              columnSpan?: T;
              rowStart?: T;
              rowSpan?: T;
              quoteFontFamily?: T;
              quoteFontSize?: T;
              quoteFontColor?: T;
              attributionFontFamily?: T;
              attributionFontSize?: T;
              attributionFontColor?: T;
              id?: T;
              blockName?: T;
            };
        dynamicQuote?:
          | T
          | {
              columnStart?: T;
              columnSpan?: T;
              rowStart?: T;
              rowSpan?: T;
              quoteFontFamily?: T;
              quoteFontSize?: T;
              quoteFontColor?: T;
              attributionFontFamily?: T;
              attributionFontSize?: T;
              attributionFontColor?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              columnStart?: T;
              columnSpan?: T;
              rowStart?: T;
              rowSpan?: T;
              objectFit?: T;
              objectPosition?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-walt_select".
 */
export interface AboutWaltSelect<T extends boolean = true> {
  headline?: T;
  subheadline?: T;
  heroImage?: T;
  introduction?: T;
  philosophy?: T;
  focusAreas?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  portrait?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  headline?: T;
  intro?: T;
  formNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-stats_select".
 */
export interface CommunityStatsSelect<T extends boolean = true> {
  totalMembers?: T;
  totalCheckIns?: T;
  totalBadgesAwarded?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-settings_select".
 */
export interface QuoteSettingsSelect<T extends boolean = true> {
  rotationMode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}